name: CI

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: verus-find

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check --verbose
      - run: cargo clippy --verbose -- --deny warnings
      - run: cargo build --verbose
      - run: git clone --depth=1 https://github.com/verus-lang/verus ${{ github.workspace }}/verus
      - run: VSTD_PATH=${{ github.workspace }}/verus/source/vstd cargo test --verbose --features test_vstd
